name: Deploy to Ubuntu Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploying to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/undangan-web
            git fetch origin master
            git reset --hard origin/master
            npm install
            npx prisma generate
            npm run build
            pm2 restart all
